version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    networks:
      - my-network
    volumes:
      - ./app/public:/app/public:rw
    ports:
      - "3333:3000"
    container_name: rce
    image: rce/node_server

networks:
  my-network:
    driver: bridge
